.github/workflows/close-prs-issues.yml

Actions setting

---

백준/1번문제/S0okJu/Q1620.py
백준/2번문제/S0okJu/Q11286.py

[S0okJu] Session02

---

백준/1번문제/S0okJu/Q11725.py
백준/2번문제/S0okJu/Q11286.py
백준/2번문제/S0okJu/Q1991.py

[S0okJu] Session03

---

백준/1번문제/최원준/Q11725.java
백준/1번문제/최원준/Q1620.java
백준/1번문제/최원준/Q9012.java
백준/2번문제/최원준/Q10799.java
백준/2번문제/최원준/Q11286.java
백준/2번문제/최원준/Q1991.java
백준/3번문제/최원준/Q1918.java
백준/3번문제/최원준/Q1967.java
백준/3번문제/최원준/Q21942.java

[최원준] Session03

---

백준/1번문제/태현/Q1747

[태현]Session04

---

백준/1번문제/최원준/Q2960.java
백준/2번문제/최원준/Q1747.java
백준/3번문제/최원준/Q22943.java

[최원준] Session04

---

백준/2번문제/태현/Q20115

[태현] Session05

---

백준/1번문제/S0okJu/Q2217.py
백준/2번문제/S0okJu/Q1747.py
백준/2번문제/S0okJu/Q20115.py

[S0okJu] Session05

---

백준/1번문제/태현/Q0655
백준/2번문제/태현/Q11726

[TaeHyun] Session06

---

백준/1번문제/S0okJu/Q2217.py
백준/1번문제/S0okJu/Q9655.py

[S0okJu] Session06

---

백준/1번문제/최원준/Q2217.java
백준/1번문제/최원준/Q9655.java
백준/2번문제/최원준/Q11726.java
백준/2번문제/최원준/Q20115.java
백준/3번문제/최원준/Q15486.java
백준/3번문제/최원준/Q2141.java

[최원준] Session06

---

백준/1번문제/태현/Q15724

[taetae] Session07

---

백준/1번문제/S0okJu/Q15724.py

[S0okJu] Session07

---

백준/1번문제/최원준/15724-2.py
백준/2번문제/최원준/2073-2.py
백준/3번문제/최원준/20542-2.py

[최원준] Session07

---

백준/1번문제/태현/Q21921

[taetae] Session08

---

백준/1번문제/최원준/Q21921.java
백준/2번문제/최원준/Q3151.java

[최원준] Session08

---

백준/1번문제/태현/Q4396

[taetae] Session09

---

백준/1번문제/S0okJu/Q15724.py
백준/2번문제/S0okJu/Q2615.py

[S0okJu] Session09

---

백준/1번문제/최원준/Q4396.java
백준/2번문제/최원준/Q2615.java
백준/3번문제/최원준/Q14719.java

[최원준] Session09

---

백준/1번문제/태현/Q14940
백준/2번문제/태현/Q2667

[TaeTae] Session10

---

백준/1번문제/S0okJu/Q14940.py
백준/2번문제/S0okJu/Q2667.py

[S0okJu] Session10

---

백준/1번문제/최원준/Q14940.java
백준/2번문제/최원준/Q2667.java
백준/3번문제/최원준/Q17836.java

[최원준] Session10

---

백준/1번문제/태현/Q5568

[taetae] Session11

---

백준/1번문제/최원준/Q5568.java
백준/2번문제/최원준/Q16508.java
백준/3번문제/최원준/Q21278.java

[최원준] Session11

---

백준/1번문제/소리/Q2253.java
백준/2번문제/소리/Q1713.java

[임소리] Session 12

---

백준/1번문제/태현/Q5212

[taetae] Session12

---

백준/1번문제/이채현/Q5212.py
백준/2번문제/이채현/Q16508.py
백준/2번문제/이채현/Q1713.py

[이채현] Session12

---

백준/1번문제/최원준/Q5212.java
백준/2번문제/최원준/Q15683.java

[최원준] Session12

---

백준/1번문제/S0okJu/Q5212.py
백준/2번문제/S0okJu/Q16508.py
백준/2번문제/S0okJu/Q1713.py

[S0okJu] Session12

---

백준/1번문제/이채현/Q11663.py
백준/2번문제/이채현/Q2470.py

[이채현] Session13

---

백준/1번문제/Q11663

[taetae] Session13

---

백준/1번문제/소리/Q11663.java
백준/1번문제/소리/Q2253.java
백준/2번문제/소리/Q1713.java

[임소리] Session 13

---

백준/1번문제/S0okJu/Q11663.py

[S0okJu] Session13

---

백준/1번문제/최원준/Q11663_2.java
백준/2번문제/최원준/Q2470_2.java
백준/3번문제/최원준/Q2473.java

[최원준] Session13

---

백준/1번문제/이채현/Q15649.py
백준/2번문제/이채현/Q1182.py

[이채현] Session14

---

백준/1번문제/소리/Q11663.java
백준/1번문제/소리/Q15649.java

[임소리] Session14

---

백준/1번문제/태현/Q15649

[taetae] Session14

---

백준/1번문제/이채현/Q2630.py
백준/2번문제/이채현/Q1074.py

[이채현] Session15

---

백준/1번문제/소리/Q2630.java

[임소리] Session15

---

백준/1번문제/S0okJu/Q2630.py

[S0okJu] Session15

---

백준/1번문제/최원준/Q2630.java
백준/2번문제/최원준/Q1074_2.java
백준/3번문제/최원준/Q4256.java

[최원준] Session15

---

백준/1번문제/이채현/Q20438.py

[이채현] Session16

---

백준/2번문제/소리/Q21318.java

[임소리] Session16

---

백준/1번문제/S0okJu/Q20438.py

[S0okJu] Session16

---

백준/1번문제/최원준/Q20438.java
백준/2번문제/최원준/Q21318.java
백준/3번문제/최원준/Q1749.java

[최원준] Session16

---

백준/1번문제/이채현/Q18352.py
백준/2번문제/이채현/Q11657.py

[이채현] Session17

---

백준/1번문제/S0okJu/Q18352.py
백준/1번문제/S0okJu/Q20438.py

[S0okJu] Session17

---

백준/1번문제/최원준/Q18352.java
백준/2번문제/최원준/Q11657.java
백준/3번문제/최원준/Q1719.java

[최원준] Session17

---

백준/1번문제/이채현/Q1717.py
백준/3번문제/이채현/Q1976.py

[이채현] Session18
